Add !tqsmute and /tqsmute
Erisa/Cliptok pull request #189
Opened 2024-02-22 21:04 UTC by FloatingMilkshake

This PR closes #168.

Adds two new commands, `!tqsmute` and `/tqsmute`, that Technical Queries Slayer members can use to temp-mute other members.

TQS members can provide a reason for the mute, but cannot change the duration, nor can they mute other TQS members or staff. Mute duration can be configured with `tqsMuteDurationHours` in config.json.

The `tqsmute` commands can only be used in tech support channels and their threads.
<img width="867" alt="image" src="https://github.com/Erisa/Cliptok/assets/51096169/25e3661a-c7ca-453e-8e09-c4219b80d6e7">

When TQS members use the slash command to mute a member, it is suggested that they create a modmail thread to provide moderators with context & prompt further mod action. Unfortunately this is not done when `!tqsmute` is used, as I wasn't sure what the best way to get this message across privately would be—ephemeral messages only work with slash commands, and I don't really like the idea of a DM.
<img width="1022" alt="image" src="https://github.com/Erisa/Cliptok/assets/51096169/89f9276a-29e2-469f-9098-6db760e54bbf">

TQS mutes are logged in the standard mod log channel, and are also sent to the investigations channel.
<img width="617" alt="image" src="https://github.com/Erisa/Cliptok/assets/51096169/7c36ef54-2f9d-48eb-b5a4-afca107fafbb">

TQS mutes are stored in the db the same way regular mutes are. There is no special flag in the db to identify that they are TQS mutes, but there is a note on the log in log channels (see above). If a moderator uses the `mute` command to apply a standard mute to a TQS-muted member, the mute in the db is overwritten. 

This PR also updates the `unmute` command to remove both the standard Muted role and the TQS Muted role. There is not a separate command for removing TQS mutes only.

2024-03-03 18:30 UTC, Erisa requested changes
Some review comments.

Also, currently if one leaves the server while TQS Muted it ends up removing the mute (even from the db), most likely there is some on server leave/join logic that is interfering.

Feel free to add a simple bool with default value to mute objects if you need a way to tell the difference between the two types.

2024-03-03 18:30 UTC, Erisa commented on Commands/InteractionCommands/MuteInteractions.cs
> +            [Option("reason", "The reason for the mute.")] string reason = "No reason specified.")
This should be required for a slash command, it encourages setting a good reason and makes the UX better when entering name and reason.
```suggestion
            [Option("reason", "The reason for the mute.")] string reason)
```

2024-03-03 18:30 UTC, Erisa commented on Helpers/MuteHelpers.cs
> +                            output.dmMessage = await naughtyMember.SendMessageAsync($"{Program.cfgjson.Emoji.Muted} You have been temporarily muted in **tech support channels only** in **{guild.Name}
```suggestion
                            output.dmMessage = await naughtyMember.SendMessageAsync($"{Program.cfgjson.Emoji.Muted} You have been temporarily muted, in **tech support channels only**, in **{guild.Name}** for **{TimeHelpers.TimeToPrettyFormat(muteDuration, false)}** pending action from a Moderator." +
```

2024-03-04 04:14 UTC, FloatingMilkshake commented
All resolved. I hadn't thought to look at member join checks, but those consider the Muted role when checking whether to reapply a mute. Updated to also consider the TQS mute role.

2024-04-27 13:48 UTC, Erisa approved these changes

2024-04-27 18:01 UTC, kotx commented
beans

2024-04-27 23:45 UTC, merged