Add #insiders-info interactions
Erisa/Cliptok pull request #255
Opened 2024-12-31 04:26 UTC by FloatingMilkshake

Adds the stuff for #insiders-info. Closes #252.

Adds `/send-insiders-info-buttons`, which sends a simple message (only allowed in the configured `insiderInfo` channel) with a couple of buttons. One button pops open a select menu that allows users to change their Insider roles. The other (after a confirmation message) grants users a chat role (config `insidersChat` under `userRoles`). If the user already has the role, it will be removed. **This role must be added to config before merging!!** We don't have a role for this yet, so I left it unconfigured.

The select menu is sent in an ephemeral message after users click the "Choose your Insider roles" button so that it can dynamically reflect the state of their Insider roles. Users can select roles to get them, and unselect them to lose them. 

https://github.com/user-attachments/assets/ded08485-0a30-403d-af24-6338d209121e

2024-12-31 13:00 UTC, Erisa commented on config.json
> +    "insiderChat": 0,
```suggestion
    "insiderChat": 1323636793668800547,
```

2024-12-31 13:29 UTC, Erisa commented on Commands/InteractionCommands/InsidersInteractions.cs
> +        [SlashRequireHomeserverPerm(ServerPermLevel.TrialModerator), SlashCommandPermissions(permissions: DiscordPermission.ModerateMembers)]
Due to the fact it only needs to be used once and can have mildly chaotic consequences if misused, this should be restricted to someone who is either lead mod **or** has bot owner rights. (i.e. myself, you, and timewalker)

2025-01-01 00:41 UTC, FloatingMilkshake commented on Commands/InteractionCommands/InsidersInteractions.cs
> +        [SlashRequireHomeserverPerm(ServerPermLevel.TrialModerator), SlashCommandPermissions(permissions: DiscordPermission.ModerateMembers)]
Understood! It is restricted to #insiders-info already, but I have also restricted it to lead mods & bot owners in https://github.com/Erisa/Cliptok/pull/255/commits/baf81d9f3e4988ff4ab985cc5a4832f1b0a9a0bf

Also: `SlashRequireHomeserverPermAttribute` lacked the `OwnerOverride` option, so added it to get this done

2025-01-02 15:25 UTC, Erisa commented on config.json
> +  "insidersChannel": 187649467611086849,
This is a duplicate of `insiderCommandLockedToChannel`

2025-01-02 15:29 UTC, Erisa requested changes

2025-01-02 15:29 UTC, Erisa commented on Commands/InteractionCommands/InsidersInteractions.cs
> +            if (Program.cfgjson.InsiderInfoChannel != 0 && ctx.Channel.Id != Program.cfgjson.InsiderInfoChannel)
This should also check that `insidersChannel` is specified in the config, to avoid `<#0>` being sent which is difficult to debug

2025-01-02 15:29 UTC, Erisa commented on Events/InteractionEvents.cs
> +                if (member.Roles.Contains(insiderChatRole))
This should also check if you have any of the insider update roles and mention that you already have channel access

2025-01-02 15:30 UTC, Erisa commented on config.json
> +  "insidersChannel": 187649467611086849,
`insidersChannel` is a better name so lets consolidate older usage into that name but still accept `insiderCommandLockedToChannel` an alias for both. Might require some custom logic in ConfigJson struct

2025-01-02 17:07 UTC, FloatingMilkshake commented on config.json
> +  "insidersChannel": 187649467611086849,
How do you want this to work? Accept both values in config, but require it to be referenced as `Program.cfgjson.InsidersChannel`?

2025-01-02 17:38 UTC, Erisa commented on config.json
> +  "insidersChannel": 187649467611086849,
One variable thats used but that accepts two json names.. probably done by setting both variables and then setting one to the other. It sounds annoying but makes more sense when configuring

2025-01-02 17:42 UTC, FloatingMilkshake commented on Commands/InteractionCommands/InsidersInteractions.cs
> +            if (Program.cfgjson.InsiderInfoChannel != 0 && ctx.Channel.Id != Program.cfgjson.InsiderInfoChannel)
Done in https://github.com/Erisa/Cliptok/pull/255/commits/4d349942bb8862f0faef533dc71c50924dce456f; a hardcoded string "#insiders" is sent if the config value is missing (and a warning is logged) because I don't feel the command should fail just for that

2025-01-03 01:54 UTC, Erisa approved these changes

2025-01-03 01:57 UTC, merged